RANKINGS = {
    'Argentina': 1,
    'Spain': 2,
    'France': 3,
    'England': 4,
    'Portugal': 5,
    'Brazil': 6,
    'Morocco': 7,
    'Netherlands': 8,
    'Belgium': 9,
    'Germany': 10,
    'Croatia': 11,
    'Colombia': 13,
    'Mexico': 14,
    'Senegal': 15,
    'USA': 16,
    'Uruguay': 17,
    'Japan': 18,
    'Switzerland': 19,
    'Iran': 20,
    'Denmark': 21,
    'Turkey': 22,
    'Austria': 23,
    'Ecuador': 24,
    'South Korea': 25,
    'Nigeria': 26,
    'Australia': 27,
    'Algeria': 28,
    'Egypt': 29,
    'Canada': 30,
    'Norway': 31,
    "Côte d'Ivoire": 33,
    'Panama': 34,
    'Sweden': 38,
    'Czechia': 39,
    'Paraguay': 40,
    'Scotland': 43,
    'DR Congo': 45,
    'Tunisia': 46,
    'Uzbekistan': 50,
    'Qatar': 55,
    'Iraq': 56,
    'South Africa': 60,
    'Saudi Arabia': 61,
    'Jordan': 63,
    'Bosnia and Herzegovina': 64,
    'Cape Verde': 66,
    'Ghana': 73,
    'New Zealand': 85,
    'Haiti': 82,
    'Curacao': 83
}